[package]
name = "rowdy"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]
build = "build.rs"

[lib]
name = "rowdy"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[features]
default = ["simple_authenticator"]

# Build with clippy lints
clippy_lints = ["clippy"]
# A simple file based authenticator
simple_authenticator = ["csv", "ring"]
# LDAP based authenticator
ldap_authenticator = ["openldap", "strfmt"]

[dependencies]
biscuit = { git = "https://github.com/lawliet89/biscuit", rev = "991a2f1cb3c5dc0774a132ec3a78fb36530189cc" }
chrono = { version = "0.3", features = ["serde"] }
hyper = "0.10"
log = "0.3"
rocket = "= 0.2.4"
rocket_codegen = "= 0.2.4"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
unicase="1.4"
uuid = { version = "0.4", features = ["use_std", "v5", "serde"] }

# Optional dependencies that are activated by the various features
clippy = { version = "=0.0.122", optional = true }
csv = { version = "0.15", optional = true }
openldap = { version = "1.2.1", optional = true }
ring = { version = "*", optional = true } # rust-jwt has this as its dependency
strfmt = { version = "0.1.5", optional = true }

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "uuid"]

[dev-dependencies]
serde_test = "0.9"
rocket = { version = "*", features = ["testing"] }

[build-dependencies]
ansi_term = "0.9"
version_check = "0.1"

[workspace]
members = ["cli"]
