[package]
name = "rowdy-lib"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[lib]
name = "rowdy"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[features]
default = ["simple_authenticator"]

# Build with clippy lints
clippy_lints = ["clippy"]
# A simple file based authenticator
simple_authenticator = ["csv", "ring"]

[dependencies]
chrono = { version = "0.3", features = ["serde"] }
hyper = "0.10"
jwt = { git = "https://github.com/lawliet89/rust-jwt", rev = "4f3165ccaad16e05aaefa9d0f8edfbbf874c37b2" }
log = "0.3"
rocket = "0.2.2"
rocket_codegen = "0.2.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
unicase="1.4"
uuid = { version = "0.4", features = ["use_std", "v5", "serde"] }

# Optional dependencies that are activated by the various features
clippy = { version = "*", optional = true }
csv = { version = "0.15", optional = true }
ring = { version = "*", optional = true } # rust-jwt has this as its dependency

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "uuid"]

[dev-dependencies]
serde_test = "0.9"
rocket = { version = "*", features = ["testing"] }

[workspace]
members = ["bin"]
