[package]
name = "rowdy-cli"
version = "0.0.5-dev"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[[bin]]
name = "rowdy-cli"
path = "src/main.rs"
test = true
doc = false

[dependencies]
docopt = "0.7"
log = "0.3"
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rowdy = { path = "../", features = ["simple_authenticator", "ldap_authenticator"] }
rustc-serialize = "0.3"
serde = "1.0"
serde_json = "1.0"
