[package]
name = "rowdy"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[[bin]]
name = "rowdy"
path = "src/main.rs"
test = true
doc = false

[dependencies]
docopt = "0.7"
log = "0.3"
rocket = "0.2.2"
rocket_codegen = "0.2.2"
rowdy-lib = { path = "../" }
rustc-serialize = "0.3"
serde = "0.9"
serde_json = "0.9"

[dev-dependencies]
rocket = { version = "*", features = ["testing"] }
